# Generated by Django 5.0.2 on 2024-03-20 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('codigoUnico', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('idBarbero', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correoE', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correoE', models.CharField(max_length=45)),
                ('celular', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoRol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoServicio', models.CharField(max_length=45)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=45)),
                ('idAgenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.agenda')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='idBarbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.barbero'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('idBarbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.barbero')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.cliente'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField()),
                ('horaFinal', models.TimeField()),
                ('diaDescanso', models.CharField(max_length=10)),
                ('idBarbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.barbero')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicioAdicional', models.CharField(max_length=45)),
                ('montoPagado', models.IntegerField()),
                ('idAgenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.agenda')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.rol'),
        ),
        migrations.AddField(
            model_name='barbero',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.rol'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('correoE', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=30)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.rol')),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamiento.servicio'),
        ),
    ]
